yatube/about/urls.py
# файл about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
# posts/urls.py
from django.urls import path

from . import views
app_name = 'posts'
urlpatterns = [
    path('', views.index, name="index_p"),
    path('group/<slug:slug>/', views.group_posts, name="group_list"),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name="post_create"),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace="posts")),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),

]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()
COUNT_OF_SORT = 10
COUNT_OF_CUT = 15


class Group(models.Model):
    title = models.CharField(max_length=200,
                             verbose_name='Название группы')
    slug = models.SlugField(unique=True,
                            verbose_name='Условная ссылка на группу')
    description = models.TextField(verbose_name='Описание группы')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст поста', help_text='Текст')
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата публикации')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор поста'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        related_name='posts',
        on_delete=models.SET_NULL,
        verbose_name='Группа поста',
        help_text='Текст нового поста'
    )

    def __str__(self):
        # выводим текст поста
        return self.text[:COUNT_OF_CUT]

    class Meta:
        ordering = ['-pub_date']

yatube/posts/forms.py
# forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')
        labels = {
            'text': 'Текст',
            'group': 'Группа'
        }
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Выберите группу по желанию'
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

from .models import Post, Group, User
from .forms import PostForm

from django.core.paginator import Paginator
from django.shortcuts import render

POSTS_ON_PAGE = 10


def get_page(request, post_list):
    paginator = Paginator(post_list, POSTS_ON_PAGE)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


def index(request):
    template = 'posts/index.html'
    post_list = Post.objects.all()
    page_obj = get_page(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_obj = get_page(request, post_list)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    user = get_object_or_404(User, username=username)
    post_list = user.posts.all()
    page_obj = get_page(request, post_list)
    context = {
        'author': user,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, id=post_id)
    context = {
        'post': post,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', post.author)
        return render(request, template, {'form': form})
    return render(request, template, {'form': form})


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post.id)
    form = PostForm(request.POST or None, instance=post,)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post.id)
    return render(
        request,
        template,
        {'form': form,
         'is_edit': True,
         'post_id': post.id
         },
    )

yatube/templates/posts/create_post.html
<!DOCTYPE html> 
{% extends "base.html" %}
{% block content %}
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                Новый пост             
              </div>
              <div class="card-body">
                  <form method="post">
                  {{ form.as_p }}
                  {% csrf_token %}
                  {% if field.help_text %}
                    <small
                        id="{{ field.id_for_label }}-help"
                        class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                     {% if is_edit %}
                       Сохранить
                     {% else %}
                       Добавить
                     {% endif %}
                    </button>
                  </div>
                  </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

yatube/templates/posts/group_list.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% extends 'base.html' %}
{% block title %}{{ group.title }}{% endblock %}
{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text }}</p>
    </article>
    <hr>
   {% endfor %}
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}<h1>{{ group.title }}</h1>{% endblock %}
<p>{{ group.description }}</p>
{% block content %}
    {% for post in page_obj %}
        <article>
            <ul>
                <li>
                    Автор: {{ post.author.get_full_name }}
                </li>
                <li>
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
            </ul>
            <p>{{ post.text }}</p>
            {% if post.group %}
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
        </article>
        <hr>
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
    Пост {{ detail.text|truncatechars:30 }}
{% endblock %}
{% block content %}
    <div class="row">
        <aside class="col-12 col-md-3">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
                {% if detail.group %}
                    <li class="list-group-item">
                    Группа: {{ post.group.title }}
                    {% if post.group %}
                        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
                    {% endif %}
                    </a>
                {% endif %}
                </li>
                <li class="list-group-item">
                    Автор: {{ user.username }}
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Всего постов автора: <span>{{ post.author.posts.count }}</span>
                </li>
                <li class="list-group-item">

                    <a href="{% url 'posts:profile' post.author %}">
                        все посты пользователя
                    </a>
                </li>
            </ul>
        </aside>
        <article class="col-12 col-md-9">
            <p>
                {{ detail.text }}
            </p>
            <a href={% url 'posts:post_edit' post.id %}>
                редактировать запись
            </a>
        </article>

    </div>
{% endblock %}

yatube/templates/posts/profile.html
{% block title %}Профиль пользователя {{ user.username }}{% endblock %}
 {% block content %}
      <div class="container py-5">
       <h1>Все посты пользователя {{ user.username }}</h1>
        <h3>Всего постов: {{ author.posts.count }} </h3>
              {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ user.username }}
                    {% if post.group %}
                    <a href="{% url 'posts:group_list' post.group.slug %}">все посты пользователя</a>
                    {% endif %}

            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>
            {{ post.text }}
          </p>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
        </article>
            {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
        <hr>
        {% if not foorloop.last %}
        {% endif %}
        {% endfor %}
          {% include 'posts/includes/paginator.html' %}
      </div>
 {% endblock %}